### ISSUE TITLE
My buttons need an exorcist 

### ISSUE THREAD

**Issue by Lionstein** [Lionstein/modularity-mindfulness#1]
I'm not sure how the buttons got so drunk, but I can't figure out how to reverse or fix this, or whats causing it.
@charlie-quinn

**Comment by charlie-quinn** [comment]
@Lionstein 
- [ ] make sure your buttons also include the `.btn` class
- [ ] don't forget to close your `<a>` tags
- [ ] wrap your buttons inside of a `<div>` and add the `.push` class to give them a nice margin-bottom below

**Comment by charlie-quinn** [comment]
@Lionstein don't forget to close this issue once it's been resolved ✅
