### ISSUE TITLE
Nav hover colour error

### ISSUE THREAD

**Issue by Lionstein** [Lionstein/modularity-mindfulness#2]
I have one error in Markbot that none of us have been able to figure out. Its "The website isn't functioning as expected: the background-color, color, or border-color of the navigation link don't change when hovered"
@charlie-quinn

**Comment by charlie-quinn** [comment]
@Lionstein please push your most recent commit(s) and I'll take a peek.

**Comment by Lionstein** [comment]
It's been committed now, all good to go.

**Comment by charlie-quinn** [comment]
- [ ] remove the `btn` class from your `<li>` tags (navigation links aren't typically styled as buttons)
- [ ] add a `border-bottom` to your links to get [this nice underline + hover](https://cl.ly/e9afb9296e00)

**Comment by Lionstein** [comment]
Success, thank you!
